# Generated by Django 5.2.16 on 2026-07-27 21:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('display_type', models.CharField(choices=[('touch', 'Touch'), ('non_touch', 'Non-Touch')], max_length=20)),
                ('model_number', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('processor_generation', models.CharField(blank=True, default='', max_length=50)),
                ('ram_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('qc_status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('warranty_days', models.PositiveSmallIntegerField(choices=[(0, 'No Warranty'), (7, '7 Days'), (15, '15 Days'), (30, '30 Days')], default=0)),
                ('area', models.CharField(choices=[('comp_a', 'comp.A'), ('comp_b', 'comp.B'), ('comp_c', 'comp.C'), ('comp_d', 'comp.D')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_laptops',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='laptop_company_idx'), models.Index(fields=['model_number'], name='laptop_model_idx'), models.Index(fields=['qc_status'], name='laptop_qc_status_idx'), models.Index(fields=['area'], name='laptop_area_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ram_gb__gte', 1)), name='laptop_ram_gte_1'), models.CheckConstraint(condition=models.Q(('storage_gb__gte', 1)), name='laptop_storage_gte_1'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='laptop_quantity_gte_1'), models.CheckConstraint(condition=models.Q(('wholesale_price__gte', 0)), name='laptop_wholesale_price_gte_0'), models.CheckConstraint(condition=models.Q(('retail_price__gte', 0)), name='laptop_retail_price_gte_0'), models.CheckConstraint(condition=models.Q(('retail_price__gte', models.F('wholesale_price'))), name='laptop_retail_gte_wholesale'), models.CheckConstraint(condition=models.Q(('warranty_days__in', [0, 7, 15, 30])), name='laptop_valid_warranty_days')],
            },
        ),
    ]
