# Generated by Django 5.2.16 on 2026-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('in_service', 'In Service')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['inventory_status'], name='laptop_inv_status_idx'),
        ),
    ]
