# Generated by Django 5.2.16 on 2026-08-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_laptop_inventory_status_alter_laptop_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('in_stock_g', 'In Stock G'), ('in_service', 'In Service')], default='in_stock', max_length=20),
        ),
    ]
