# Generated by Django 5.2.16 on 2026-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_order_orderdeletionrequest_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laptop',
            name='laptop_quantity_gte_1',
        ),
        migrations.AddConstraint(
            model_name='laptop',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='laptop_quantity_gte_0'),
        ),
    ]
