# Generated by Django 5.2.16 on 2026-08-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_laptop_laptop_quantity_gte_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('in_stock_g', 'In Stock G'), ('in_service', 'In Service'), ('sold', 'Sold')], default='in_stock', max_length=20),
        ),
    ]
