# Generated by Django 5.2.16 on 2026-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_laptop_inventory_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='laptop',
            name='laptop_quantity_gte_0',
        ),
        migrations.AddConstraint(
            model_name='laptop',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 1)), name='laptop_quantity_exactly_1'),
        ),
    ]
