# Generated by Django 5.2.16 on 2026-08-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_laptop_laptop_quantity_gte_0_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at', '-id'), 'permissions': [('view_sales_report', 'Can view total sales report')]},
        ),
    ]
