# Generated by Django 5.2.16 on 2026-08-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory_status_before_sale',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
