# Generated by Django 5.2.16 on 2026-08-15 19:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_orderitem_inventory_status_before_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=150)),
                ('company', models.CharField(db_index=True, max_length=100)),
                ('display_type', models.CharField(choices=[('touch', 'Touch'), ('non_touch', 'Non-Touch')], max_length=20)),
                ('model_number', models.CharField(db_index=True, max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('processor_generation', models.CharField(blank=True, default='', max_length=50)),
                ('ram_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('storage_type', models.CharField(choices=[('ssd', 'SSD'), ('hdd', 'HDD')], max_length=10)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('issue', models.TextField()),
                ('service_rack', models.CharField(choices=[('SER-A', 'SER-A'), ('SER-B', 'SER-B'), ('SER-C', 'SER-C')], max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_service', 'In Service'), ('repair_completed', 'Repair Completed'), ('swap_requested', 'Swap Requested'), ('ready_for_dispatch', 'Ready For Dispatch'), ('stocked_in', 'Stocked In'), ('dispatched', 'Dispatched')], db_index=True, default='received', max_length=30)),
                ('repair_notes', models.TextField(blank=True, default='')),
                ('stocked_in_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_returns',
                'ordering': ('-created_at', '-id'),
                'permissions': [('assign_return_priority', 'Can assign return priority'), ('stock_in_return', 'Can stock in returned laptop'), ('export_return', 'Can export return records')],
            },
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_unit_price_gte_zero',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_line_total_gte_zero',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_line_total_gte_0'),
        ),
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='stocked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stocked_in_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='stocked_in_laptop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_returns', to='inventory.laptop'),
        ),
        migrations.AddField(
            model_name='return',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status', 'created_at'], name='return_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['priority', 'created_at'], name='return_priority_created_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['technician', 'status'], name='return_tech_status_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['service_rack'], name='return_rack_idx'),
        ),
    ]
