# Generated by Django 5.2.16 on 2026-08-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='service_rack',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
