# Generated by Django 5.2.16 on 2026-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_return_inventory_service_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='seal_status',
            field=models.CharField(choices=[('seal_broken', 'Seal Broken'), ('sealed', 'Sealed')], db_index=True, default='sealed', max_length=20),
        ),
        migrations.AddField(
            model_name='return',
            name='warranty_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
    ]
